# Generated by Django 4.0.5 on 2022-06-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=200)),
            ],
        ),
    ]
